### ISSUE TITLE
Don't compile with kernel 5.0.94

### ISSUE THREAD

**Issue by sateuwdie** [christopherkobayashi/dahdi-linux#1]
On kernel 5.0.94 gcc 11 give me this error

```
/tmp/MG/dahdi-complete-022023git/linux/drivers/dahdi/dahdi-base.c: In function ‘dahdi_proc_open’:
/tmp/MG/dahdi-complete-022023git/linux/drivers/dahdi/dahdi-base.c:1009:50: error: implicit declaration of function ‘pde_data’ [-Werror=implicit-function-declaration]
 1009 |         return single_open(file, dahdi_seq_show, pde_data(inode));
      |                                                  ^~~~~~~~
/tmp/MG/dahdi-complete-022023git/linux/drivers/dahdi/dahdi-base.c:1009:50: warning: passing argument 3 of ‘single_open’ makes pointer from integer without a cast [-Wint-conversion]
 1009 |         return single_open(file, dahdi_seq_show, pde_data(inode));
      |                                                  ^~~~~~~~~~~~~~~
      |                                                  |
      |                                                  int
In file included from /tmp/MG/dahdi-complete-022023git/linux/drivers/dahdi/dahdi-base.c:42:
./include/linux/seq_file.h:150:68: note: expected ‘void *’ but argument is of type ‘int’
  150 | int single_open(struct file *, int (*)(struct seq_file *, void *), void *);
```
